### ISSUE TITLE
Introduce variables to disable "Program" and "Campaign" related models

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_marketo#10]
There are a few tables in Marketo that cause extreme slowness with the connector, and are therefore not recommended for syncing.  

Our package was built before this guidance, and therefore makes use of tables that are becoming increasingly unpopular.  Let's refactor this package to introduce variables that disable "program" and "campaign."  These variables should be disabled as default, and customers will need to opt-in (enable) the variable to get this logic.  This will be considered a breaking change.

![Screen Shot 2021-05-10 at 8 38 20 AM](https://user-images.githubusercontent.com/54283769/117685775-15c85680-b16b-11eb-8704-e47025a5d834.png)

**Comment by rcaddell** [comment]
Hello @fivetran-kristin,
Expanding on this, according to Marketo, if your Marketo account has native CRM sync enabled, you will not be able to target the Company object, it is blocked with an access denied message.  

https://developers.marketo.com/rest-api/lead-database/companies/

**Comment by fivetran-kristin** [comment]
This work has been completed and now available!

Release is here: https://github.com/fivetran/dbt_marketo/releases/tag/v0.4.0
